Repository yandexdataschool/Practical_RL, pull requests merged in 2020-05, with the labels that each got.

#405 ValueTargets typos
  week06_policy_based/a2c-optional.ipynb
  week09_policy_II/ppo.ipynb
Labels: bug, text in notebooks

#410 week7: correct interchanged comments in basic_model_torch.py
  week07_seq2seq/basic_model_torch.py
Labels: text in notebooks

#414 [Week 4: CartPole] Clarify nonlinearities
  week04_approx_rl/seminar_pytorch.ipynb
  week04_approx_rl/seminar_tf.ipynb
Labels: text in notebooks

#412 [Week 4: Recap PyTorch] Update Colab deps & remove __future__ import
  week04_[recap]_deep_learning/seminar_pytorch.ipynb
Labels: colab-compatibility, maintenance

#407 [recap ml] Cleanup
  week01_intro/primer_python_for_ml/recap_ml.ipynb
Labels: maintenance

#413 [Week 4: Recap TF] Fix nonexistent variable (#192) & other cleanup
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
Labels: bug

#388 Unify code for evaluation
  week1_intro/crossentropy_method.ipynb
  week1_intro/deep_crossentropy_method.ipynb
  week1_intro/submit.py
  week4_approx/dqn_atari.ipynb
  week4_approx/dqn_atari_pytorch.ipynb
  week4_approx/practice_approx_qlearning.ipynb
  week4_approx/practice_approx_qlearning_pytorch.ipynb
  week4_approx/submit.py
  week5_policy_based/practice_a3c.ipynb
  week5_policy_based/practice_reinforce.ipynb
  week5_policy_based/practice_reinforce_pytorch.ipynb
Labels: coursera, maintenance

#419 [spring20] Fixes
  week04_[recap]_deep_learning/seminar_pytorch.ipynb
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
  week04_approx_rl/homework_pytorch_debug.ipynb
  week04_approx_rl/homework_pytorch_main.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week09_policy_II/ppo.ipynb
Labels: maintenance

#421 [Week 4] Hotfix for missing Gym import
  week4_approx/submit.py
Labels: bug, coursera

#422 [Week 2] Add assertion for incorrect handling of negative Q-values
  week02_value_based/seminar_vi.ipynb
Labels: asserts in notebooks

#428 [Week 8] Remove mention of Gym leaderboard
  week08_pomdp/homework_common_part2.ipynb
Labels: text in notebooks

#432 [Week 5] Fix comment
  week5_policy_based/practice_reinforce.ipynb
  week5_policy_based/practice_reinforce_pytorch.ipynb
Labels: coursera, maintenance, text in notebooks

#429 [Week7 seq2seq] Fix wrong description of attention in week7 in bonus_pytorch.ipynb
  week07_seq2seq/bonus_pytorch.ipynb
Labels: text in notebooks

#430 [spring20] Miscellaneous fixes
  week01_intro/crossentropy_method.ipynb
  week01_intro/deep_crossentropy_method.ipynb
  week02_value_based/mdp.py
  week02_value_based/seminar_vi.ipynb
  week03_model_free/homework.ipynb
  week04_[recap]_deep_learning/seminar_pytorch.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_pytorch.ipynb
  week04_approx_rl/seminar_tf.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week08_pomdp/theano_optional_recurrence_tutorial.ipynb
Labels: maintenance

#425 [Week 10] Clarify how MCTS works & cleanup notebook
  week10_planning/seminar_MCTS.ipynb
Labels: text in notebooks

#431 Merge master into coursera (May 2020)
  week1_intro/crossentropy_method.ipynb
  week1_intro/primer/recap_ml.ipynb
  week1_intro/primer/recap_pytorch.ipynb
  week2_model_based/mdp.py
  week2_model_based/practice_vi.ipynb
  week3_model_free/qlearning.ipynb
  week4_approx/dqn_atari.ipynb
  week4_approx/dqn_atari_pytorch.ipynb
  week4_approx/practice_approx_qlearning.ipynb
  week4_approx/practice_approx_qlearning_pytorch.ipynb
  week5_policy_based/practice_reinforce.ipynb
  week5_policy_based/practice_reinforce_pytorch.ipynb
  week5_policy_based/submit.py
  week6_outro/bandits.ipynb
  week6_outro/practice_mcts.ipynb
  week6_outro/seq2seq/practice_pytorch.ipynb
  week6_outro/seq2seq/practice_tf.ipynb
  week6_outro/seq2seq/voc.py
Labels: coursera, maintenance, text in notebooks
