Repository yandexdataschool/Practical_RL, pull requests merged in 2020-04, with the labels that each got.

#334 [Week 6] Avoid AttributeError on TF BasicTranslationModel
  week6_outro/seq2seq/practice_tf.ipynb
Labels: coursera

#336 Automate Colab setup in most notebooks
  week01_intro/crossentropy_method.ipynb
  week01_intro/deep_crossentropy_method.ipynb
  week01_intro/seminar_gym_interface.ipynb
  week02_value_based/seminar_vi.ipynb
  week03_model_free/homework.ipynb
  week03_model_free/seminar_qlearning.ipynb
  week04_[recap]_deep_learning/seminar_pytorch.ipynb
  week04_approx_rl/seminar_pytorch.ipynb
  week05_explore/week5.ipynb
  week06_policy_based/a2c-optional.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week07_seq2seq/practice_torch.ipynb
  week08_pomdp/practice_pytorch.ipynb
  week09_policy_II/ppo.ipynb
  week09_policy_II/seminar_TRPO_pytorch.ipynb
  week10_planning/seminar_MCTS.ipynb
Labels: maintenance

#340 [Week 6] Fix wrong objective formula in REINFORCE
  week06_policy_based/reinforce_lasagne.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
Labels: bug, priority:high

#350 [Week 4 Recap] Remove old Practice TF notebook (#191)
  week04_[recap]_deep_learning/practice_tensorflow.ipynb
Labels: maintenance

#351 Upgrade notebook JSON to v4
  week04_[recap]_deep_learning/practice_lasagne.ipynb
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
  week04_approx_rl/homework_lasagne.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_lasagne.ipynb
  week07_[recap]_rnn/seminar_lasagne.ipynb
  week07_[recap]_rnn/seminar_lasagne_ingraph.ipynb
  week07_[recap]_rnn/seminar_tf.ipynb
  week07_seq2seq/bonus.ipynb
  week07_seq2seq/practice_theano.ipynb
  week08_pomdp/homework_common_part2.ipynb
  week08_pomdp/practice_tensorflow.ipynb
  week08_pomdp/practice_theano.ipynb
  week08_pomdp/theano_optional_recurrence_tutorial.ipynb
Labels: maintenance

#356 [Week 1] Add Colab init block in Gym Interface notebook
  week1_intro/gym_interface.ipynb
Labels: colab-compatibility, coursera

#354 Cleanup inconsistent placeholders
  week01_intro/crossentropy_method.ipynb
  week01_intro/deep_crossentropy_method.ipynb
  week01_intro/primer_python_for_ml/recap_ml.ipynb
  week01_intro/project_starter_evolution_strategies.ipynb
  week02_value_based/seminar_vi.ipynb
  week03_model_free/homework.ipynb
  week03_model_free/seminar_qlearning.ipynb
  week04_[recap]_deep_learning/practice_lasagne.ipynb
  week04_[recap]_deep_learning/seminar_pytorch.ipynb
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
  week04_approx_rl/homework_lasagne.ipynb
  week04_approx_rl/homework_pytorch_debug.ipynb
  week04_approx_rl/homework_pytorch_main.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_lasagne.ipynb
  week04_approx_rl/seminar_pytorch.ipynb
  week04_approx_rl/seminar_tf.ipynb
  week05_explore/week5.ipynb
  week06_policy_based/reinforce_lasagne.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week07_[recap]_rnn/seminar_lasagne.ipynb
  week07_[recap]_rnn/seminar_lasagne_ingraph.ipynb
  week07_[recap]_rnn/seminar_pytorch.ipynb
  week07_[recap]_rnn/seminar_tf.ipynb
  week07_seq2seq/bonus.ipynb
  week07_seq2seq/practice_tf.ipynb
  week07_seq2seq/practice_theano.ipynb
  week07_seq2seq/practice_torch.ipynb
  week08_pomdp/practice_pytorch.ipynb
  week08_pomdp/practice_tensorflow.ipynb
  week08_pomdp/practice_theano.ipynb
  week08_pomdp/theano_optional_recurrence_tutorial.ipynb
  week09_policy_II/seminar_TRPO_pytorch.ipynb
  week09_policy_II/seminar_TRPO_tensorflow.ipynb
  week09_policy_II/seminar_TRPO_theano.ipynb
  week10_planning/seminar_MCTS.ipynb
Labels: maintenance

#358 Update setup_colab.sh
  setup_colab.sh
Labels: colab-compatibility

#359 Update Colab initialization code in some notebooks
  week01_intro/crossentropy_method.ipynb
  week01_intro/deep_crossentropy_method.ipynb
  week01_intro/seminar_gym_interface.ipynb
  week03_model_free/homework.ipynb
  week03_model_free/seminar_qlearning.ipynb
  week10_planning/seminar_MCTS.ipynb
Labels: colab-compatibility

#364 [Week 3] Improve homework
  week03_model_free/homework.ipynb
Labels: maintenance

#363 [Week 3] Fix Colab initialization in homework part 2
  week03_model_free/homework.ipynb
Labels: colab-compatibility

#365 [Week 5] Improve Honor assignment
  week5_policy_based/atari_util.py
  week5_policy_based/practice_a3c.ipynb
  week5_policy_based/submit.py
Labels: colab-compatibility, coursera

#367 [Week 8] Port TF fixes from Coursera
  week08_pomdp/atari_util.py
  week08_pomdp/practice_tensorflow.ipynb
Labels: maintenance

#353 Rebuild Coursera branch off master
  Amazon GPU howto.md
  Dockerfile
  README.md
  docker/Dockerfile
  docker/README.md
  docker/run_jupyter.sh
  extra_packages.md
  week1_intro/crossentropy_method.ipynb
  week1_intro/deep_crossentropy_method.ipynb
  week1_intro/gym_interface.ipynb
  week1_intro/primer/recap_ml.ipynb
  week1_intro/primer/recap_tensorflow.ipynb
  week2_model_based/practice_vi.ipynb
  week3_model_free/experience_replay.ipynb
  week3_model_free/qlearning.ipynb
  week3_model_free/qlearning.py
  week3_model_free/sarsa.ipynb
  week4_approx/dqn_atari.ipynb
  week4_approx/practice_approx_qlearning.ipynb
  week5_policy_based/practice_reinforce.ipynb
  week6_outro/bandits.ipynb
  week6_outro/practice_mcts.ipynb
  week6_outro/seq2seq/practice_tf.ipynb
Labels: coursera

#375 Add Colab init cells in all notebooks
  week1_intro/crossentropy_method.ipynb
  week1_intro/deep_crossentropy_method.ipynb
  week1_intro/gym_interface.ipynb
  week1_intro/primer/recap_ml.ipynb
  week1_intro/primer/recap_tensorflow.ipynb
  week2_model_based/practice_vi.ipynb
  week3_model_free/experience_replay.ipynb
  week3_model_free/qlearning.ipynb
  week3_model_free/sarsa.ipynb
  week4_approx/dqn_atari.ipynb
  week4_approx/practice_approx_qlearning.ipynb
  week5_policy_based/practice_a3c.ipynb
  week5_policy_based/practice_reinforce.ipynb
  week6_outro/bandits.ipynb
  week6_outro/practice_mcts.ipynb
  week6_outro/seq2seq/practice_tf.ipynb
Labels: colab-compatibility, coursera

#377 Revert Taxi-v3 to v2 because gym in Coursera is too old
  week1_intro/crossentropy_method.ipynb
  week3_model_free/experience_replay.ipynb
  week3_model_free/qlearning.ipynb
Labels: coursera

#376 Silence apt-get in Colab
  setup_colab.sh
Labels: colab-compatibility

#378 [Week 4] Add TF global variable initializer
  week4_approx/practice_approx_qlearning.ipynb
Labels: coursera

#380 Backport fixes from Coursera (mostly Colab)
  week01_intro/crossentropy_method.ipynb
  week01_intro/deep_crossentropy_method.ipynb
  week01_intro/primer_python_for_ml/recap_ml.ipynb
  week01_intro/seminar_gym_interface.ipynb
  week02_value_based/seminar_vi.ipynb
  week03_model_free/seminar_qlearning.ipynb
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_tf.ipynb
  week05_explore/week5.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week07_seq2seq/practice_tf.ipynb
  week08_pomdp/practice_tensorflow.ipynb
  week10_planning/seminar_MCTS.ipynb
Labels: colab-compatibility

#381 Fix Colab init in recaps
  week1_intro/primer/recap_ml.ipynb
  week1_intro/primer/recap_tensorflow.ipynb
Labels: colab-compatibility

#383 Week 07 get rid of randomness of Vocab.from_lines
  week07_seq2seq/voc.py
Labels: bug

#387 Workaround for Taxi-v2/v3 available in Coursera xor Colab
  week1_intro/crossentropy_method.ipynb
  week3_model_free/experience_replay.ipynb
  week3_model_free/qlearning.ipynb
Labels: colab-compatibility, coursera

#385 Fix redundant .setup_complete check
  week04_[recap]_deep_learning/seminar_tensorflow.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_tf.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week07_seq2seq/practice_tf.ipynb
Labels: colab-compatibility

#386 Simplify Colab initialization
  week04_approx_rl/seminar_pytorch.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
Labels: colab-compatibility

#391 [Week 6] Restore grader deleted during rebuild from master
  week6_outro/seq2seq/practice_tf.ipynb
Labels: coursera

#392 Miscellaneous fixes for spring20
  week01_intro/crossentropy_method.ipynb
  week03_model_free/seminar_qlearning.ipynb
  week05_explore/week5.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week07_seq2seq/practice_tf.ipynb
Labels: maintenance

#382 Unify code for evaluation
  week01_intro/deep_crossentropy_method.ipynb
  week04_approx_rl/homework_pytorch_main.ipynb
  week04_approx_rl/homework_tf.ipynb
  week04_approx_rl/seminar_pytorch.ipynb
  week04_approx_rl/seminar_tf.ipynb
  week06_policy_based/reinforce_pytorch.ipynb
  week06_policy_based/reinforce_tensorflow.ipynb
  week08_pomdp/practice_pytorch.ipynb
  week08_pomdp/practice_tensorflow.ipynb
Labels: maintenance

#394 DQN preprocessing fixes
  week4_approx/dqn_atari.ipynb
Labels: bug, coursera

#395 Fix breakout env version
  week4_approx/dqn_atari.ipynb
Labels: coursera, maintenance

#341 Coursera PyTorch: primer + Week 4 + Week 5 REINFORCE + Week 6 Seq2seq
  week1_intro/primer/notmnist.py
  week1_intro/primer/recap_pytorch.ipynb
  week4_approx/atari_wrappers.py
  week4_approx/dqn_atari_pytorch.ipynb
  week4_approx/practice_approx_qlearning_pytorch.ipynb
  week4_approx/utils.py
  week5_policy_based/practice_reinforce_pytorch.ipynb
  week5_policy_based/submit.py
  week6_outro/seq2seq/basic_model_torch.py
  week6_outro/seq2seq/practice_pytorch.ipynb
Labels: coursera, enhancement
