Repository yandexdataschool/Practical_RL, pull requests merged in 2020-06, with the labels that each got.

#436 Upgrade docker
  docker/Dockerfile
  docker/README.md
  docker/deeplearning.yaml
  docker/run_jupyter.sh
Labels: docker

#439 s/<EMAIL>/'your.email@example.com', s/<TOKEN>/'YourAssignmentToken'
  week1_intro/crossentropy_method.ipynb
  week1_intro/deep_crossentropy_method.ipynb
  week1_intro/gym_interface.ipynb
  week2_model_based/practice_vi.ipynb
  week3_model_free/experience_replay.ipynb
  week3_model_free/qlearning.ipynb
  week3_model_free/sarsa.ipynb
  week4_approx/dqn_atari.ipynb
  week4_approx/dqn_atari_pytorch.ipynb
  week4_approx/practice_approx_qlearning.ipynb
  week4_approx/practice_approx_qlearning_pytorch.ipynb
  week5_policy_based/practice_a3c.ipynb
  week5_policy_based/practice_reinforce.ipynb
  week5_policy_based/practice_reinforce_pytorch.ipynb
  week6_outro/bandits.ipynb
  week6_outro/practice_mcts.ipynb
  week6_outro/seq2seq/practice_pytorch.ipynb
  week6_outro/seq2seq/practice_tf.ipynb
Labels: coursera

#440 Remove Binder
  Dockerfile
  README.md
  week03_model_free/crawler_and_pacman/seminar_py2/README.md
  week03_model_free/crawler_and_pacman/seminar_py3/README.md
Labels: maintenance

#441 [Week 4: DQN Atari] Fix missing wget commands for submission
  week4_approx/dqn_atari_pytorch.ipynb
Labels: bug, colab-compatibility, coursera
